version: '3.8'

services:
  # Frontend - Vue.js Application
  frontend:
    build:
      context: ./frontend
    container_name: task-manager-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080/api
      - VITE_FIREBASE_AUTH_EMULATOR_URL=http://localhost:9099
      - VITE_FIREBASE_FIRESTORE_EMULATOR_URL=http://localhost:8081
    depends_on:
      - backend
      - firebase-emulator
    networks:
      - task-manager-network

  # Backend - Node.js/Express API
  backend:
    build:
      context: ./backend
    container_name: task-manager-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
      - FIREBASE_FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
    depends_on:
      - firebase-emulator
    networks:
      - task-manager-network

  # Firebase Emulator - Auth & Firestore
  firebase-emulator:
    build:
      context: ./firebase-emulator
    container_name: task-manager-firebase
    volumes:
      - ./firebase-emulator:/app
      - firebase-data:/app/data
    ports:
      - "9099:9099"  # Auth Emulator
      - "8081:8080"  # Firestore Emulator
      - "4000:4000"  # Emulator UI
    networks:
      - task-manager-network

  # Nginx - Web Server
  nginx:
    image: nginx:alpine
    container_name: task-manager-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - task-manager-network

networks:
  task-manager-network:
    driver: bridge

volumes:
  firebase-data: